/**
 * Spec-first Broadset development fixtures.
 *
 * The goal of this file is to demonstrate what the current BroadsetProject
 * and BroadsetDocument specifications allow, using a polished broadcast-package
 * example rather than a legacy runtime-oriented mock.
 *
 * NOTE: This fixture is intentionally large and representative. Its size is a
 * feature, not a maintenance problem: it acts as a high-coverage sample corpus
 * for renderer, playback, and format work, so it should not be split merely to
 * chase file-length metrics.
 */

const ISO_TIMESTAMP = '2026-04-06T12:00:00Z';
const PARTNER_MARK_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 180"><defs><linearGradient id="partner-gradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#3da9fc"/><stop offset="100%" stop-color="#15c39a"/></linearGradient></defs><rect width="180" height="180" rx="36" fill="#08111f"/><path d="M38 118 73 55l22 36 18-28 29 55H38Z" fill="url(#partner-gradient)"/><circle cx="120" cy="57" r="10" fill="#ffcb47"/></svg>`;
const PARTNER_MARK_DATA_URI = `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(PARTNER_MARK_SVG)}`;
const INLINE_VIDEO_PLACEHOLDER = '';
const INLINE_MEDIA_URL = 'data:application/octet-stream;base64,';

const BRAND = {
  ink: '#08111f',
  panel: '#13243c',
  panelSoft: '#1b3352',
  blue: '#3da9fc',
  cyan: '#74d9ff',
  mint: '#15c39a',
  gold: '#ffcb47',
  coral: '#ff6b7a',
  white: '#f7fbff',
  slate: '#c7d6e6',
} as const;

const BASE_STYLE = {
  opacity: 1,
} as const;

const BASE_ELEMENT = {
  locked: false,
  parentId: null,
  groupId: null,
  assetId: null,
  dataField: null,
  visibleWhen: null,
  repeater: null,
  typeConfig: null,
  componentRef: null,
  autoSize: 'fixed' as const,
  textPathElementId: null,
  booleanOperation: null,
  extensions: {},
} as const;

const SHARED_DATA_SCHEMA = {
  description: 'Live event broadcast fields for matchup, promos, lineup cards, and rolling alerts.',
  fields: [
    { name: 'homeTeam', type: 'string', label: 'Home Team', defaultValue: 'North City FC' },
    { name: 'awayTeam', type: 'string', label: 'Away Team', defaultValue: 'Harbor United' },
    { name: 'homeScore', type: 'number', label: 'Home Score', defaultValue: 2, constraints: { min: 0, max: 99 } },
    { name: 'awayScore', type: 'number', label: 'Away Score', defaultValue: 1, constraints: { min: 0, max: 99 } },
    { name: 'period', type: 'string', label: 'Match Phase', defaultValue: 'Q4 · 01:42' },
    { name: 'venue', type: 'string', label: 'Venue', defaultValue: 'Helsinki Arena' },
    { name: 'presenterName', type: 'string', label: 'Presenter', defaultValue: 'Alex Morgan' },
    { name: 'sponsorName', type: 'string', label: 'Sponsor Name', defaultValue: 'Summit Energy' },
    { name: 'sponsorVisible', type: 'boolean', label: 'Show Sponsor', defaultValue: true },
    { name: 'promoLabel', type: 'string', label: 'Promo Label', defaultValue: 'Scan for live stats' },
    { name: 'promoQr', type: 'string', label: 'Promo QR URL', defaultValue: 'https://broadset.dev/live' },
    { name: 'showPromoPanel', type: 'boolean', label: 'Show Promo Panel', defaultValue: true },
    {
      name: 'lineup',
      type: 'array',
      label: 'Top Performers',
      arrayItemSchema: [
        { name: 'slot', type: 'string', label: 'Position' },
        { name: 'name', type: 'string', label: 'Name' },
        { name: 'stat', type: 'string', label: 'Stat Line' },
      ],
    },
    {
      name: 'breakingItems',
      type: 'array',
      label: 'Ticker Items',
      arrayItemSchema: [{ name: 'headline', type: 'string', label: 'Headline' }],
    },
  ],
} as const;

const SHARED_OUTPUT = {
  frameRate: 25,
  colorSpace: 'rec709',
  dynamicRange: 'sdr',
} as const;

/**
 * Main 16:9 program package.
 * Includes all 11 current built-in element types, project-style data binding,
 * repeaters, page overrides, and modern animation definitions.
 */
export const SAMPLE_DOCUMENT = {
  id: 'doc-championship-night-main',
  name: 'Championship Night Main Show',
  documentMode: 'screen' as const,
  canvas: {
    width: 1920,
    height: 1080,
    unit: 'px' as const,
    dpi: 96,
    padding: [0, 0, 0, 0] as const,
    backgroundColor: BRAND.ink,
    backgroundMode: 'solid' as const,
    safeAreas: {
      actionSafe: [3.5, 3.5, 3.5, 3.5] as const,
      titleSafe: [5, 5, 5, 5] as const,
      custom: [
        { name: 'lower-third-zone', insets: [24, 3.5, 3.5, 3.5] as const },
        { name: 'info-panel-zone', insets: [4, 28, 32, 4] as const },
        { name: 'promo-zone', insets: [8, 4, 26, 28] as const },
      ],
    },
  },
  elements: [
    {
      ...BASE_ELEMENT,
      id: 'el-stage-bg',
      type: 'rectangle',
      name: 'Stage Background',
      locked: true,
      position: { x: 0, y: 0 },
      width: 1920,
      height: 1080,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundColor: BRAND.ink,
        backgroundGradient: 'linear-gradient(135deg, #08111f 0%, #13243c 45%, #1b3352 100%)',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-top-ribbon',
      type: 'rectangle',
      name: 'Live Header Ribbon',
      position: { x: 60, y: 52 },
      width: 920,
      height: 96,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundColor: 'rgba(8, 17, 31, 0.72)',
        borderWidth: 1,
        borderColor: 'rgba(116, 217, 255, 0.35)',
        borderRadius: [20, 28, 28, 20],
        boxShadow: '0 18px 48px rgba(0, 0, 0, 0.3)',
        backdropFilter: 'blur(12px)',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-show-title',
      type: 'text',
      name: 'Program Title',
      position: { x: 92, y: 72 },
      width: 760,
      height: 54,
      rotation: 0,
      content: '<b>CHAMPIONSHIP NIGHT</b>',
      autoSize: 'shrink-to-fit' as const,
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 38,
        fontWeight: 700,
        fontColor: BRAND.white,
        letterSpacing: 1.5,
        textTransform: 'uppercase',
        verticalAlignment: 'middle',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-show-subtitle',
      type: 'text',
      name: 'Program Subtitle',
      position: { x: 92, y: 120 },
      width: 800,
      height: 28,
      rotation: 0,
      content: 'Live from <b>Helsinki Arena</b> · Presented by Summit Energy',
      dataField: { fieldName: 'venue', overflow: 'ellipsis', prefix: 'Live from ', suffix: '' },
      autoSize: 'auto-height' as const,
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: 500,
        fontColor: BRAND.slate,
        lineHeight: 1.25,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-video-wall',
      type: 'video',
      name: 'Hero Video Wall',
      position: { x: 1160, y: 72 },
      width: 700,
      height: 394,
      rotation: 0,
      content: INLINE_VIDEO_PLACEHOLDER,
      assetId: 'asset-hero-loop',
      typeConfig: {
        loop: true,
        autoplay: true,
        muted: true,
        startTimeS: 0,
        endTimeS: null,
      },
      style: {
        ...BASE_STYLE,
        objectFit: 'cover',
        borderRadius: 24,
        borderWidth: 2,
        borderColor: 'rgba(116, 217, 255, 0.4)',
        boxShadow: '0 18px 40px rgba(0, 0, 0, 0.28)',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-video-wall-label',
      type: 'text',
      name: 'Hero Video Wall Label',
      position: { x: 1240, y: 116 },
      width: 520,
      height: 42,
      rotation: 0,
      content: '<b>LIVE FEED READY</b>',
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 22,
        fontWeight: 800,
        fontColor: BRAND.white,
        textAlignment: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1.8,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-video-wall-caption',
      type: 'text',
      name: 'Hero Video Wall Caption',
      position: { x: 1272, y: 164 },
      width: 456,
      height: 52,
      rotation: 0,
      content: 'Preview safe for sponsor stings, wipes, and halftime packages.',
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 500,
        fontColor: BRAND.slate,
        lineHeight: 1.35,
        textAlignment: 'center',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-accent-svg',
      type: 'svg',
      name: 'Broadcast Accent SVG',
      position: { x: 92, y: 176 },
      width: 120,
      height: 24,
      rotation: 0,
      content:
        '<svg viewBox="0 0 120 24" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="8" width="56" height="8" rx="4" fill="#3da9fc"/><rect x="64" y="8" width="24" height="8" rx="4" fill="#15c39a"/><rect x="96" y="8" width="24" height="8" rx="4" fill="#ffcb47"/></svg>',
      style: BASE_STYLE,
    },
    {
      ...BASE_ELEMENT,
      id: 'el-accent-arc',
      type: 'path',
      name: 'Venue Arc Path',
      position: { x: 78, y: 188 },
      width: 520,
      height: 120,
      rotation: 0,
      content: 'M 20 90 C 140 10, 360 10, 500 84',
      style: {
        ...BASE_STYLE,
        stroke: 'rgba(116, 217, 255, 0.6)',
        strokeWidth: 3,
        strokeDasharray: '10 8',
        fill: 'none',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-arc-label',
      type: 'text',
      name: 'Venue Arc Label',
      position: { x: 118, y: 202 },
      width: 420,
      height: 26,
      rotation: 0,
      content: 'INTERNATIONAL FEED · CLEAN WORLD FEED READY',
      textPathElementId: 'el-accent-arc',
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 13,
        fontWeight: 600,
        fontColor: BRAND.cyan,
        textTransform: 'uppercase',
        letterSpacing: 1.8,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-sponsor-logo',
      type: 'image',
      name: 'Sponsor Logo',
      position: { x: 1640, y: 500 },
      width: 180,
      height: 180,
      rotation: 0,
      content: PARTNER_MARK_DATA_URI,
      assetId: 'asset-sponsor-mark',
      visibleWhen: 'sponsorVisible == true',
      style: {
        ...BASE_STYLE,
        objectFit: 'contain',
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.94)',
        padding: [16, 16, 16, 16],
        boxShadow: '0 16px 36px rgba(0, 0, 0, 0.22)',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-sponsor-tag',
      type: 'text',
      name: 'Sponsor Strap',
      position: { x: 1430, y: 694 },
      width: 430,
      height: 34,
      rotation: 0,
      content: 'Presented by Summit Energy',
      dataField: { fieldName: 'sponsorName', overflow: 'ellipsis', prefix: 'Presented by ', suffix: '' },
      visibleWhen: 'sponsorVisible == true',
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: 700,
        fontColor: BRAND.white,
        textAlignment: 'right',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-info-panel',
      type: 'group',
      name: 'Primary Info Panel',
      position: { x: 78, y: 818 },
      width: 1010,
      height: 164,
      rotation: 0,
      content: '',
      componentRef: { componentId: 'cmp-info-panel-shell', overrides: { theme: 'night-final' } },
      style: {
        ...BASE_STYLE,
        backgroundColor: 'rgba(8, 17, 31, 0.82)',
        borderWidth: 1,
        borderColor: 'rgba(116, 217, 255, 0.28)',
        borderRadius: 24,
        clipChildren: true,
        boxShadow: '0 22px 50px rgba(0, 0, 0, 0.34)',
      },
      extensions: {
        'dev.broadset.sample': { role: 'info-panel', priority: 'primary' },
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-home-chip',
      type: 'rectangle',
      name: 'Home Team Chip',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 18, y: 18 },
      width: 352,
      height: 128,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundGradient: 'linear-gradient(135deg, #3da9fc 0%, #225ef7 100%)',
        borderRadius: [18, 0, 0, 18],
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-away-chip',
      type: 'rectangle',
      name: 'Away Team Chip',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 640, y: 18 },
      width: 352,
      height: 128,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundGradient: 'linear-gradient(135deg, #ff6b7a 0%, #e63f62 100%)',
        borderRadius: [0, 18, 18, 0],
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-score-divider',
      type: 'rectangle',
      name: 'Score Divider',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 370, y: 18 },
      width: 270,
      height: 128,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundColor: BRAND.panel,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-home-team',
      type: 'text',
      name: 'Home Team Name',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 38, y: 44 },
      width: 230,
      height: 42,
      rotation: 0,
      content: '<b>NORTH CITY FC</b>',
      dataField: { fieldName: 'homeTeam', overflow: 'ellipsis', prefix: '', suffix: '' },
      autoSize: 'shrink-to-fit' as const,
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 34,
        fontWeight: 700,
        fontColor: BRAND.white,
        textTransform: 'uppercase',
        letterSpacing: 1,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-away-team',
      type: 'text',
      name: 'Away Team Name',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 662, y: 44 },
      width: 230,
      height: 42,
      rotation: 0,
      content: '<b>HARBOR UNITED</b>',
      dataField: { fieldName: 'awayTeam', overflow: 'ellipsis', prefix: '', suffix: '' },
      autoSize: 'shrink-to-fit' as const,
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 34,
        fontWeight: 700,
        fontColor: BRAND.white,
        textTransform: 'uppercase',
        letterSpacing: 1,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-home-score',
      type: 'text',
      name: 'Home Score',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 270, y: 28 },
      width: 84,
      height: 82,
      rotation: 0,
      content: '2',
      dataField: { fieldName: 'homeScore', overflow: 'clip', formatPattern: '##' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 68,
        fontWeight: 700,
        fontColor: BRAND.white,
        textAlignment: 'center',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-away-score',
      type: 'text',
      name: 'Away Score',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 910, y: 28 },
      width: 64,
      height: 82,
      rotation: 0,
      content: '1',
      dataField: { fieldName: 'awayScore', overflow: 'clip', formatPattern: '##' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 68,
        fontWeight: 700,
        fontColor: BRAND.white,
        textAlignment: 'center',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-period-pill',
      type: 'rectangle',
      name: 'Period Pill',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 434, y: 38 },
      width: 142,
      height: 42,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundColor: BRAND.gold,
        borderRadius: 999,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-period-text',
      type: 'text',
      name: 'Period Text',
      parentId: 'el-info-panel',
      groupId: 'grp-info-panel',
      position: { x: 448, y: 48 },
      width: 114,
      height: 22,
      rotation: 0,
      content: 'Q4 · 01:42',
      dataField: { fieldName: 'period', overflow: 'clip', prefix: '', suffix: '' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 800,
        fontColor: BRAND.ink,
        textAlignment: 'center',
        textTransform: 'uppercase',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-clock',
      type: 'clock',
      name: 'Program Clock',
      position: { x: 1162, y: 818 },
      width: 258,
      height: 84,
      rotation: 0,
      content: 'HH:mm:ss',
      typeConfig: {
        mode: 'realtime',
        startValue: null,
        targetValue: null,
        countdownTo: null,
      },
      style: {
        ...BASE_STYLE,
        backgroundColor: 'rgba(8, 17, 31, 0.74)',
        borderRadius: 18,
        padding: [16, 18, 16, 18],
        fontFamily: 'Barlow Condensed',
        fontSize: 38,
        fontWeight: 700,
        fontColor: BRAND.white,
        textAlignment: 'center',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-promo-panel',
      type: 'group',
      name: 'Interactive Promo Panel',
      position: { x: 1432, y: 760 },
      width: 430,
      height: 246,
      rotation: 0,
      content: '',
      visibleWhen: 'showPromoPanel == true',
      booleanOperation: 'union' as const,
      style: {
        ...BASE_STYLE,
        backgroundColor: 'rgba(19, 36, 60, 0.92)',
        borderWidth: 1,
        borderColor: 'rgba(116, 217, 255, 0.35)',
        borderRadius: 20,
        clipChildren: true,
        rotateY: 8,
        translateZ: 20,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-promo-bg',
      type: 'rectangle',
      name: 'Promo Panel Background',
      parentId: 'el-promo-panel',
      groupId: 'grp-promo',
      position: { x: 0, y: 0 },
      width: 430,
      height: 246,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundGradient: 'linear-gradient(135deg, #13243c 0%, #0e1b2d 100%)',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-promo-label',
      type: 'text',
      name: 'Promo Label',
      parentId: 'el-promo-panel',
      groupId: 'grp-promo',
      position: { x: 24, y: 24 },
      width: 214,
      height: 42,
      rotation: 0,
      content: '<b>Scan for live stats</b>',
      dataField: { fieldName: 'promoLabel', overflow: 'ellipsis', prefix: '', suffix: '' },
      autoSize: 'auto-height' as const,
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 22,
        fontWeight: 700,
        fontColor: BRAND.white,
        lineHeight: 1.2,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-promo-qr',
      type: 'qrcode',
      name: 'Promo QR',
      parentId: 'el-promo-panel',
      groupId: 'grp-promo',
      position: { x: 250, y: 24 },
      width: 144,
      height: 144,
      rotation: 0,
      content: 'https://broadset.dev/live',
      dataField: { fieldName: 'promoQr', overflow: 'clip', prefix: '', suffix: '' },
      style: {
        ...BASE_STYLE,
        backgroundColor: '#ffffff',
        padding: [12, 12, 12, 12],
        borderRadius: 16,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-promo-caption',
      type: 'text',
      name: 'Promo Caption',
      parentId: 'el-promo-panel',
      groupId: 'grp-promo',
      position: { x: 24, y: 86 },
      width: 188,
      height: 84,
      rotation: 0,
      content: 'Second-screen audience data, live polls, and player cards.',
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 500,
        fontColor: BRAND.slate,
        lineHeight: 1.35,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-stats-repeater',
      type: 'group',
      name: 'Top Performers Repeater',
      position: { x: 78, y: 286 },
      width: 530,
      height: 358,
      rotation: 0,
      content: '',
      repeater: {
        dataArrayField: 'lineup',
        direction: 'vertical',
        gap: 12,
        maxItems: 4,
      },
      style: {
        ...BASE_STYLE,
        backgroundColor: 'rgba(8, 17, 31, 0.62)',
        borderRadius: 20,
        clipChildren: true,
      },
      extensions: {
        'dev.broadset.sample': { role: 'repeater-demo' },
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-stats-row-bg',
      type: 'rectangle',
      name: 'Stats Row Background',
      parentId: 'el-stats-repeater',
      groupId: 'grp-stats',
      position: { x: 12, y: 12 },
      width: 506,
      height: 72,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundColor: 'rgba(19, 36, 60, 0.8)',
        borderRadius: 14,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-stats-slot',
      type: 'text',
      name: 'Stats Position',
      parentId: 'el-stats-repeater',
      groupId: 'grp-stats',
      position: { x: 28, y: 28 },
      width: 48,
      height: 24,
      rotation: 0,
      content: '01',
      dataField: { fieldName: 'slot', overflow: 'clip', prefix: '#', suffix: '' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 24,
        fontWeight: 700,
        fontColor: BRAND.gold,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-stats-name',
      type: 'text',
      name: 'Stats Name',
      parentId: 'el-stats-repeater',
      groupId: 'grp-stats',
      position: { x: 92, y: 24 },
      width: 248,
      height: 28,
      rotation: 0,
      content: 'Taylor Brooks',
      dataField: { fieldName: 'name', overflow: 'ellipsis', prefix: '', suffix: '' },
      autoSize: 'shrink-to-fit' as const,
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 20,
        fontWeight: 700,
        fontColor: BRAND.white,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-stats-stat',
      type: 'text',
      name: 'Stats Detail',
      parentId: 'el-stats-repeater',
      groupId: 'grp-stats',
      position: { x: 92, y: 48 },
      width: 330,
      height: 20,
      rotation: 0,
      content: '18 pts · 9 ast · 4 reb',
      dataField: { fieldName: 'stat', overflow: 'ellipsis', prefix: '', suffix: '' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 500,
        fontColor: BRAND.slate,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-hero-badge',
      type: 'ellipse',
      name: 'Live Badge Orb',
      position: { x: 1010, y: 126 },
      width: 96,
      height: 96,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundGradient: 'radial-gradient(circle at 35% 35%, #74d9ff 0%, #3da9fc 38%, #13243c 100%)',
        boxShadow: '0 0 28px rgba(61, 169, 252, 0.42)',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-ticker',
      type: 'ticker',
      name: 'Breaking Ticker',
      position: { x: 0, y: 1028 },
      width: 1920,
      height: 52,
      rotation: 0,
      content:
        '["North City FC clinches playoff berth", "Player of the match interview next", "Studio analysis available in 90 seconds"]',
      typeConfig: {
        speed: 96,
        direction: 'left',
        gap: 48,
        paused: false,
      },
      style: {
        ...BASE_STYLE,
        backgroundColor: 'rgba(8, 17, 31, 0.94)',
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: 600,
        fontColor: BRAND.white,
        padding: [14, 24, 14, 24],
      },
    },
  ],
  animations: [
    {
      elementId: 'el-hero-badge',
      config: {
        timelines: [
          {
            id: 'tl-hero-pulse',
            name: 'Hero Pulse',
            durationMs: 1800,
            loop: 'ping-pong',
            loopCount: null,
            keyframes: [
              {
                name: 'hero-start',
                action: 'none',
                offsetMs: 0,
                properties: {
                  opacity: { type: 'number', value: 0.45, easing: 'linear' },
                  scale: { type: 'number', value: 0.82, easing: 'spring-gentle' },
                  translateX: { type: 'number', value: 0, easing: 'ease-in-out' },
                },
              },
              {
                name: 'hero-peak',
                action: 'none',
                offsetMs: 900,
                properties: {
                  opacity: { type: 'number', value: 1, easing: 'linear' },
                  scale: { type: 'number', value: 1.18, easing: 'spring-bouncy' },
                  translateX: { type: 'number', value: 96, easing: 'ease-in-out' },
                },
              },
              {
                name: 'hero-end',
                action: 'none',
                offsetMs: 1800,
                properties: {
                  opacity: { type: 'number', value: 0.7, easing: 'linear' },
                  scale: { type: 'number', value: 0.92, easing: 'spring-stiff' },
                  translateX: { type: 'number', value: 36, easing: 'ease-in-out' },
                },
              },
            ],
            childTimelines: [],
            audioCues: [],
          },
        ],
        stateTimelineBindings: [],
        modifierTimelineBindings: [],
        textAnimator: null,
      },
    },
    {
      elementId: 'el-home-score',
      config: {
        timelines: [
          {
            id: 'tl-home-score-count',
            name: 'Home Score Count',
            durationMs: 1200,
            loop: 'none',
            loopCount: null,
            keyframes: [
              {
                name: 'score-start',
                action: 'none',
                offsetMs: 0,
                properties: {
                  textContent: {
                    type: 'string',
                    value: '0',
                    easing: 'counting',
                    countingFormat: { decimalPlaces: 0 },
                  },
                  opacity: { type: 'number', value: 0.55, easing: 'linear' },
                },
              },
              {
                name: 'score-finish',
                action: 'none',
                offsetMs: 1200,
                properties: {
                  textContent: {
                    type: 'string',
                    value: '2',
                    easing: 'counting',
                    countingFormat: { decimalPlaces: 0 },
                  },
                  opacity: { type: 'number', value: 1, easing: 'linear' },
                },
              },
            ],
            childTimelines: [],
            audioCues: [],
          },
        ],
        stateTimelineBindings: [],
        modifierTimelineBindings: [],
        textAnimator: null,
      },
    },
    {
      elementId: 'el-promo-panel',
      config: {
        timelines: [
          {
            id: 'tl-promo-in',
            name: 'Promo In',
            durationMs: 900,
            loop: 'none',
            loopCount: null,
            keyframes: [
              {
                name: 'promo-hidden',
                action: 'none',
                offsetMs: 0,
                properties: {
                  opacity: { type: 'number', value: 0, easing: 'linear' },
                  translateY: { type: 'number', value: 28, easing: 'ease-out' },
                  scale: { type: 'number', value: 0.94, easing: 'ease-out' },
                },
              },
              {
                name: 'promo-visible',
                action: 'none',
                offsetMs: 900,
                properties: {
                  opacity: { type: 'number', value: 1, easing: 'linear' },
                  translateY: { type: 'number', value: 0, easing: 'spring-gentle' },
                  scale: { type: 'number', value: 1, easing: 'spring-gentle' },
                },
              },
            ],
            childTimelines: [],
            audioCues: [],
          },
          {
            id: 'tl-promo-out',
            name: 'Promo Out',
            durationMs: 600,
            loop: 'none',
            loopCount: null,
            keyframes: [
              {
                name: 'promo-start',
                action: 'none',
                offsetMs: 0,
                properties: {
                  opacity: { type: 'number', value: 1, easing: 'linear' },
                  translateY: { type: 'number', value: 0, easing: 'ease-in' },
                  scale: { type: 'number', value: 1, easing: 'ease-in' },
                },
              },
              {
                name: 'promo-end',
                action: 'none',
                offsetMs: 600,
                properties: {
                  opacity: { type: 'number', value: 0, easing: 'linear' },
                  translateY: { type: 'number', value: 36, easing: 'ease-in' },
                  scale: { type: 'number', value: 0.9, easing: 'ease-in' },
                },
              },
            ],
            childTimelines: [],
            audioCues: [],
          },
        ],
        stateTimelineBindings: [
          { stateName: 'IN', timelineId: 'tl-promo-in' },
          { stateName: 'OUT', timelineId: 'tl-promo-out' },
        ],
        modifierTimelineBindings: [],
        textAnimator: null,
      },
    },
  ],
  pages: [
    {
      id: 'page-live',
      name: 'Live Main',
      overrides: [],
      locale: 'en-GB',
      extensions: {},
    },
    {
      id: 'page-open',
      name: 'Program Open',
      overrides: [
        {
          elementId: 'el-show-title',
          content: '<b>CHAMPIONSHIP NIGHT</b><br /><span style="color:#74d9ff">Season Finale</span>',
        },
        {
          elementId: 'el-show-subtitle',
          content: 'Opening sequence · Studio anchor on camera',
          style: { fontColor: BRAND.cyan },
        },
        {
          elementId: 'el-promo-panel',
          visible: true,
        },
      ],
      locale: 'en-GB',
      extensions: {},
    },
    {
      id: 'page-halftime',
      name: 'Half-Time Analysis',
      overrides: [
        {
          elementId: 'el-show-title',
          content: '<b>HALF-TIME REPORT</b>',
        },
        {
          elementId: 'el-period-text',
          content: 'HALF-TIME',
        },
        {
          elementId: 'el-top-ribbon',
          style: { backgroundColor: 'rgba(21, 195, 154, 0.18)', borderColor: 'rgba(21, 195, 154, 0.4)' },
        },
        {
          elementId: 'el-ticker',
          content: '["Analysis begins now", "Tactical board coming up", "Second-half keys in 60 seconds"]',
        },
      ],
      locale: 'en-GB',
      extensions: {},
    },
    {
      id: 'page-fulltime',
      name: 'Final Result',
      overrides: [
        {
          elementId: 'el-show-title',
          content: '<b>FULL-TIME</b>',
        },
        {
          elementId: 'el-show-subtitle',
          content: 'North City FC advances to the championship series',
          style: { fontColor: BRAND.gold },
        },
        {
          elementId: 'el-clock',
          visible: false,
        },
        {
          elementId: 'el-video-wall',
          visible: false,
        },
      ],
      locale: 'en-GB',
      extensions: {},
    },
  ],
  dataSchema: SHARED_DATA_SCHEMA,
  output: SHARED_OUTPUT,
  extensions: {
    'dev.broadset.sample': {
      purpose: 'Spec coverage reference fixture',
      profile: 'broadcast-package',
      reviewedAt: ISO_TIMESTAMP,
    },
  },
} as const;

/**
 * Lightweight vertical adaptation used to demonstrate BroadsetProject
 * template groups and multi-format packaging.
 */
export const SAMPLE_SOCIAL_DOCUMENT = {
  id: 'doc-championship-night-vertical',
  name: 'Championship Night Social Vertical',
  documentMode: 'screen' as const,
  canvas: {
    width: 1080,
    height: 1920,
    unit: 'px' as const,
    dpi: 96,
    padding: [0, 0, 0, 0] as const,
    backgroundColor: BRAND.ink,
    backgroundMode: 'solid' as const,
    safeAreas: {
      actionSafe: [3.5, 3.5, 3.5, 3.5] as const,
      titleSafe: [5, 5, 5, 5] as const,
    },
  },
  elements: [
    {
      ...BASE_ELEMENT,
      id: 'el-social-bg',
      type: 'rectangle',
      name: 'Vertical Background',
      locked: true,
      position: { x: 0, y: 0 },
      width: 1080,
      height: 1920,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundGradient: 'linear-gradient(180deg, #08111f 0%, #13243c 100%)',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-social-title',
      type: 'text',
      name: 'Vertical Title',
      position: { x: 80, y: 120 },
      width: 920,
      height: 120,
      rotation: 0,
      content: '<b>CHAMPIONSHIP NIGHT</b>',
      autoSize: 'shrink-to-fit' as const,
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 72,
        fontWeight: 700,
        fontColor: BRAND.white,
        textAlignment: 'center',
        textTransform: 'uppercase',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-social-score',
      type: 'group',
      name: 'Vertical Score Group',
      position: { x: 80, y: 1460 },
      width: 920,
      height: 220,
      rotation: 0,
      content: '',
      style: {
        ...BASE_STYLE,
        backgroundColor: 'rgba(8, 17, 31, 0.84)',
        borderRadius: 24,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-social-home',
      type: 'text',
      name: 'Vertical Home Team',
      parentId: 'el-social-score',
      groupId: 'grp-social-score',
      position: { x: 40, y: 40 },
      width: 500,
      height: 40,
      rotation: 0,
      content: 'North City FC',
      dataField: { fieldName: 'homeTeam', overflow: 'ellipsis', prefix: '', suffix: '' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 28,
        fontWeight: 700,
        fontColor: BRAND.white,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-social-away',
      type: 'text',
      name: 'Vertical Away Team',
      parentId: 'el-social-score',
      groupId: 'grp-social-score',
      position: { x: 40, y: 132 },
      width: 500,
      height: 40,
      rotation: 0,
      content: 'Harbor United',
      dataField: { fieldName: 'awayTeam', overflow: 'ellipsis', prefix: '', suffix: '' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Inter',
        fontSize: 28,
        fontWeight: 700,
        fontColor: BRAND.white,
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-social-home-score',
      type: 'text',
      name: 'Vertical Home Score',
      parentId: 'el-social-score',
      groupId: 'grp-social-score',
      position: { x: 720, y: 24 },
      width: 120,
      height: 64,
      rotation: 0,
      content: '2',
      dataField: { fieldName: 'homeScore', overflow: 'clip', formatPattern: '##' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 58,
        fontWeight: 700,
        fontColor: BRAND.blue,
        textAlignment: 'center',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-social-away-score',
      type: 'text',
      name: 'Vertical Away Score',
      parentId: 'el-social-score',
      groupId: 'grp-social-score',
      position: { x: 720, y: 116 },
      width: 120,
      height: 64,
      rotation: 0,
      content: '1',
      dataField: { fieldName: 'awayScore', overflow: 'clip', formatPattern: '##' },
      style: {
        ...BASE_STYLE,
        fontFamily: 'Barlow Condensed',
        fontSize: 58,
        fontWeight: 700,
        fontColor: BRAND.coral,
        textAlignment: 'center',
      },
    },
    {
      ...BASE_ELEMENT,
      id: 'el-social-qr',
      type: 'qrcode',
      name: 'Vertical QR',
      position: { x: 390, y: 820 },
      width: 300,
      height: 300,
      rotation: 0,
      content: 'https://broadset.dev/social',
      dataField: { fieldName: 'promoQr', overflow: 'clip', prefix: '', suffix: '' },
      style: {
        ...BASE_STYLE,
        backgroundColor: '#ffffff',
        padding: [18, 18, 18, 18],
        borderRadius: 24,
      },
    },
  ],
  animations: [],
  pages: [
    {
      id: 'page-social-live',
      name: 'Social Live',
      overrides: [],
      locale: 'en-GB',
      extensions: {},
    },
    {
      id: 'page-social-final',
      name: 'Social Final',
      overrides: [{ elementId: 'el-social-title', content: '<b>FINAL SCORE</b>' }],
      locale: 'en-GB',
      extensions: {},
    },
  ],
  dataSchema: SHARED_DATA_SCHEMA,
  output: SHARED_OUTPUT,
  extensions: {
    'dev.broadset.sample': {
      purpose: 'Vertical reference variant',
      linkedGroup: 'tg-championship-night',
    },
  },
} as const;

/**
 * Full project wrapper showcasing the top-level BroadsetProject container.
 */
export const SAMPLE_PROJECT = {
  $schema: 'https://schema.broadset.dev/v1/project.json',
  schemaVersion: 1,
  id: 'proj-championship-night',
  name: 'Championship Night Broadcast Package',
  createdAt: ISO_TIMESTAMP,
  updatedAt: ISO_TIMESTAMP,
  settings: {
    fonts: [
      {
        family: 'Inter',
        variants: [
          { weight: 400, style: 'normal' },
          { weight: 500, style: 'normal' },
          { weight: 700, style: 'normal' },
        ],
        source: { kind: 'system' },
      },
      {
        family: 'Barlow Condensed',
        variants: [
          { weight: 600, style: 'normal' },
          { weight: 700, style: 'normal' },
        ],
        source: { kind: 'system' },
      },
    ],
    palette: [BRAND.ink, BRAND.panel, BRAND.blue, BRAND.cyan, BRAND.mint, BRAND.gold, BRAND.coral, BRAND.white],
    defaultDocumentMode: 'screen' as const,
  },
  assets: [
    {
      id: 'asset-sponsor-mark',
      name: 'Partner Mark',
      kind: 'image',
      mimeType: 'image/svg+xml',
      source: { type: 'url', url: PARTNER_MARK_DATA_URI },
      metadata: { usage: 'sponsor' },
    },
    {
      id: 'asset-hero-loop',
      name: 'Arena Crowd Loop',
      kind: 'video',
      mimeType: 'video/mp4',
      source: { type: 'url', url: INLINE_MEDIA_URL },
      metadata: { durationSeconds: 18, loopable: true },
    },
    {
      id: 'asset-audio-whoosh',
      name: 'Broadcast Whoosh',
      kind: 'audio',
      mimeType: 'audio/mpeg',
      source: { type: 'url', url: INLINE_MEDIA_URL },
      metadata: { usage: 'transition' },
    },
  ],
  documents: [SAMPLE_DOCUMENT, SAMPLE_SOCIAL_DOCUMENT],
  templateGroups: [
    {
      groupId: 'tg-championship-night',
      name: 'Championship Night Package',
      members: [
        { documentId: 'doc-championship-night-main', role: '16:9', label: 'Main Program HD' },
        { documentId: 'doc-championship-night-vertical', role: '9:16', label: 'Social Vertical' },
      ],
    },
  ],
  extensions: {
    'dev.broadset.sample': {
      purpose: 'Repository reference package for spec-led development',
      updatedAt: ISO_TIMESTAMP,
    },
  },
} as const;
