import { describe, expect, it } from 'vitest';

import { canRoundTrip, exportPdfBytes, importPdfDocument, readPdfRoundTripMetadata } from './index';
import { makeDocument, makeElement, makeStyle } from './test-helpers';

/**
 * P6.4a acceptance tests — the XMP + marked-content fast-path import that
 * round-trips Broadset-exported PDFs. These tests export a document with
 * the P6.3 pipeline and then re-import it via the fast-path, verifying
 * that at least the document id, element id list, and per-element
 * `/BSET` marked-content kinds survive the trip.
 */

describe('P6.4a PDF import fast path — canRoundTrip', () => {
  /**
   * @description Broadset-exported PDFs MUST be recognised as
   * round-trippable — they carry the `broadset:` XMP packet the fast
   * path needs to hydrate document state without operator extraction.
   */
  it('recognises a Broadset-exported PDF as round-trippable', async () => {
    const doc = makeDocument({
      id: 'roundtrip-doc-001',
      elements: [
        makeElement('rectangle', { id: 'rect-rt', style: makeStyle() }),
      ],
    });

    const bytes = await exportPdfBytes(doc);

    expect(await canRoundTrip(bytes)).toBe(true);
  });

  /**
   * @description A byte stream that does not begin with `%PDF-` MUST NOT
   * be reported as round-trippable.
   */
  it('rejects non-PDF input', async () => {
    const garbage = new Uint8Array([0x01, 0x02, 0x03, 0x04]);

    expect(await canRoundTrip(garbage)).toBe(false);
  });

  /**
   * @description A PDF without the `broadset:` XMP packet (a third-party
   * export) MUST NOT be reported as round-trippable — it lands on the
   * P6.4b operator extraction path instead.
   */
  it('rejects a PDF without a broadset: XMP packet', async () => {
    // Minimal bare PDF generated by hand — no broadset: metadata.
    const bytes = new TextEncoder().encode('%PDF-1.7\n%EOF\n');

    expect(await canRoundTrip(bytes)).toBe(false);
  });
});

describe('P6.4a PDF import fast path — importPdfDocument', () => {
  /**
   * @description The fast-path import hydrates the document id from the
   * XMP packet on the document catalog so reconciliation can match the
   * re-import against the last-known Broadset state.
   */
  it('hydrates the document id from the broadset: XMP packet', async () => {
    const doc = makeDocument({
      id: 'fast-path-doc-id-42',
      elements: [makeElement('rectangle', { id: 'rect-one', style: makeStyle() })],
    });

    const bytes = await exportPdfBytes(doc);
    const result = await importPdfDocument(bytes);

    expect(result.document.id).toBe('fast-path-doc-id-42');
  });

  /**
   * @description The fast-path import recovers every element id from the
   * XMP packet + marked-content property dicts. Element geometry lands
   * with the P6.4b operator extraction pass, but the id list must survive
   * the P6.4a pipeline so reconciliation can track identity.
   */
  it('recovers every element id from the XMP packet', async () => {
    const doc = makeDocument({
      id: 'fast-path-multi',
      elements: [
        makeElement('rectangle', { id: 'rect-a', style: makeStyle() }),
        makeElement('text', { id: 'text-b', content: 'Hello', style: makeStyle() }),
        makeElement('ellipse', { id: 'ellipse-c', style: makeStyle() }),
      ],
    });

    const bytes = await exportPdfBytes(doc);
    const result = await importPdfDocument(bytes);
    const ids = result.document.elements.map((el) => el.id);

    expect(ids).toContain('rect-a');
    expect(ids).toContain('text-b');
    expect(ids).toContain('ellipse-c');
  });

  /**
   * @description Marked-content property dicts carry each element's type
   * (`/Kind`), which the importer must preserve so `text-b` round-trips
   * as a text element rather than a generic rectangle placeholder.
   */
  it('recovers each element type from the marked-content /Kind', async () => {
    const doc = makeDocument({
      id: 'fast-path-kinds',
      elements: [
        makeElement('rectangle', { id: 'rect-kind', style: makeStyle() }),
        makeElement('text', { id: 'text-kind', content: 'Hi', style: makeStyle() }),
        makeElement('ellipse', { id: 'ellipse-kind', style: makeStyle() }),
      ],
    });

    const bytes = await exportPdfBytes(doc);
    const result = await importPdfDocument(bytes);

    const byId = new Map(result.document.elements.map((el) => [el.id, el.type]));

    expect(byId.get('rect-kind')).toBe('rectangle');
    expect(byId.get('text-kind')).toBe('text');
    expect(byId.get('ellipse-kind')).toBe('ellipse');
  });
});

describe('P6.4a PDF import fast path — readPdfRoundTripMetadata', () => {
  /**
   * @description The metadata reader returns the XMP packet and collected
   * marked-content tags for the reconciliation pipeline (P6.5). The XMP
   * packet's `documentId` and `elements[]` fingerprints are the primary
   * round-trip recovery path.
   */
  it('returns the XMP packet and collected marked-content tags', async () => {
    const doc = makeDocument({
      id: 'rt-metadata-doc',
      elements: [
        makeElement('rectangle', { id: 'rt-rect', style: makeStyle() }),
        makeElement('ellipse', { id: 'rt-ellipse', style: makeStyle() }),
      ],
    });

    const bytes = await exportPdfBytes(doc);
    const metadata = await readPdfRoundTripMetadata(bytes);

    expect(metadata.xmp).not.toBeNull();

    if (metadata.xmp !== null) {
      expect(metadata.xmp.documentId).toBe('rt-metadata-doc');
      expect(metadata.xmp.elements).toHaveLength(2);
    }

    const tagKinds = metadata.markedContentTags.map((t) => t.kind);

    expect(tagKinds).toContain('rectangle');
    expect(tagKinds).toContain('ellipse');
  });
});
