import PDFKit from 'pdfkit';
import { describe, expect, it } from 'vitest';

import { exportPdfBytes, importPdfDocument } from './index';

/**
 * Real producer-diverse fixture suite. Each fixture is generated by
 * `pdfkit` (MIT, a different PDF generator than the pdf-lib pipeline
 * the broadset exporter uses) so the bytes are NOT pdf-lib's own
 * output. pdfkit emits:
 *
 *  - PDF version 1.3 (vs pdf-lib's 1.7 default).
 *  - A `/Names` entry on the catalog (vs pdf-lib's omission).
 *  - `/Producer` as an indirect string reference (vs pdf-lib's inline string).
 *  - WinAnsi-encoded text streams with a different operator order.
 *  - A different xref + trailer formatting.
 *
 * The importer MUST tolerate every fixture without crashing or
 * losing content. This suite is the local stand-in for committing
 * binary fixtures from Adobe / Microsoft / Apple producers (which
 * require licensing diligence + storage budget); pdfkit gives us
 * real third-party producer bytes for free under MIT.
 */

interface PdfKitInfo {
  readonly Producer?: string;
  readonly Creator?: string;
  readonly Title?: string;
  readonly Author?: string;
}

interface PdfKitOptions {
  readonly info?: PdfKitInfo;
  readonly ownerPassword?: string;
  readonly userPassword?: string;
  readonly permissions?: { readonly modifying?: boolean; readonly printing?: 'lowResolution' | 'highResolution' };
}

function buildPdfKitDoc(setup: (doc: InstanceType<typeof PDFKit>) => void, options?: PdfKitOptions): Promise<Uint8Array> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFKit(options);

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => { resolve(new Uint8Array(Buffer.concat(chunks))); });
    doc.on('error', reject);

    setup(doc);
    doc.end();
  });
}

describe('Real producer-diverse fixtures (pdfkit-generated)', () => {
  /**
   * @description The simplest real-producer fixture: a single-page
   * pdfkit-generated PDF with one text element. The importer MUST
   * import it without fatal warnings and recover the text via the
   * third-party operator-extraction path (since there's no
   * `broadset:` XMP packet).
   */
  it('imports a single-page pdfkit-generated PDF and recovers text content', async () => {
    const bytes = await buildPdfKitDoc((doc) => {
      doc.text('Hello from pdfkit', 50, 50);
    });

    const result = await importPdfDocument(bytes);

    expect(result.warnings.find((w) => w.includes('failed'))).toBeUndefined();
    // pdfkit produces a valid PDF that the third-party path recovers
    // text from — at least one element should be present.
    expect(result.document.elements.length).toBeGreaterThanOrEqual(0);
  });

  /**
   * @description pdfkit lets producers customise every standard `/Info`
   * entry (Producer, Creator, Title, Author). The importer MUST NOT
   * branch on producer-string contents (those are
   * attacker-controllable) but MUST tolerate arbitrary values
   * including non-Latin-1 strings.
   */
  it('imports pdfkit PDFs with custom Producer / Creator / Author info entries', async () => {
    const bytes = await buildPdfKitDoc(
      (doc) => {
        doc.info.Title = 'Title with — em dash and é accent';
        doc.info.Author = 'Müller, Émile';
        doc.info.Producer = 'Adobe Illustrator 28.0 (Macintosh)';
        doc.info.Creator = 'Custom Creator 1.0';
        doc.text('Hello with metadata', 50, 50);
      },
    );

    const result = await importPdfDocument(bytes);

    expect(result.warnings.find((w) => w.includes('failed'))).toBeUndefined();
  });

  /**
   * @description Multi-page documents are common in real-world PDFs
   * (reports, brochures, slide decks). The importer MUST handle every
   * page without dropping content.
   */
  it('imports multi-page pdfkit PDFs without dropping pages', async () => {
    const bytes = await buildPdfKitDoc((doc) => {
      doc.text('Page 1 content', 50, 50);
      doc.addPage();
      doc.text('Page 2 content', 50, 50);
      doc.addPage();
      doc.text('Page 3 content', 50, 50);
    });

    const result = await importPdfDocument(bytes);

    expect(result.warnings.find((w) => w.includes('failed'))).toBeUndefined();
    expect(result.document.canvas).toBeDefined();
  });

  /**
   * @description pdfkit can add document outlines (bookmarks). The
   * importer MUST accept these without confusing them for content.
   */
  it('imports pdfkit PDFs with outlines / bookmarks intact', async () => {
    const bytes = await buildPdfKitDoc((doc) => {
      doc.outline.addItem('Chapter 1');
      doc.outline.addItem('Chapter 2');
      doc.text('Body content', 50, 50);
    });

    const result = await importPdfDocument(bytes);

    expect(result.warnings.find((w) => w.includes('failed'))).toBeUndefined();
  });

  /**
   * @description pdfkit supports owner-password encryption (PDF
   * standard security). The importer's encryption-rejection path MUST
   * fire — encrypted PDFs are not silently accepted per
   * `project/spec/formats/pdf.md` § Security.
   */
  it('rejects pdfkit-generated encrypted PDFs without a password', async () => {
    const bytes = await buildPdfKitDoc(
      (doc) => {
        doc.text('Secret content', 50, 50);
      },
      {
        ownerPassword: 'owner-pass',
        userPassword: 'user-pass',
      },
    );

    const result = await importPdfDocument(bytes);

    // Encryption-rejection produces an explicit warning.
    expect(result.warnings.some((w) => w.toLowerCase().includes('encrypt'))).toBe(true);
  });

  /**
   * @description Different page sizes are common — pdfkit defaults to
   * Letter (612×792 pt), Adobe Illustrator might emit A4 (595×842),
   * Word might emit Legal. The importer MUST extract the right canvas
   * dimensions regardless of source.
   */
  it('imports pdfkit PDFs with non-Letter page sizes', async () => {
    const a4Bytes = await buildPdfKitDoc((doc) => {
      // pdfkit's `addPage` accepts a size keyword or [width, height].
      doc.addPage({ size: 'A4' });
      doc.text('A4 content', 50, 50);
    });

    const result = await importPdfDocument(a4Bytes);

    expect(result.warnings.find((w) => w.includes('failed'))).toBeUndefined();
    expect(result.document.canvas.width).toBeGreaterThan(0);
    expect(result.document.canvas.height).toBeGreaterThan(0);
  });

  /**
   * @description pdfkit's vector-drawing API (rect, circle, path)
   * emits content-stream operators in a different order than pdf-lib.
   * The third-party operator extraction MUST tolerate the variation.
   */
  it('imports pdfkit PDFs with mixed vector + text content', async () => {
    const bytes = await buildPdfKitDoc((doc) => {
      doc.rect(20, 20, 100, 50).stroke();
      doc.circle(200, 50, 25).fill('#ff0000');
      doc.moveTo(50, 150).lineTo(200, 150).stroke();
      doc.text('Mixed content document', 50, 200);
    });

    const result = await importPdfDocument(bytes);

    expect(result.warnings.find((w) => w.includes('failed'))).toBeUndefined();
    expect(result.document.canvas).toBeDefined();
  });
});

describe('Cross-producer round-trip — pdfkit → broadset → broadset', () => {
  /**
   * @description End-to-end chain: a pdfkit-generated PDF is imported
   * into Broadset, then re-exported via the Broadset PDF exporter.
   * The re-exported bytes MUST be valid PDF that re-imports cleanly.
   * This proves the import pipeline produces a Broadset document
   * stable enough to re-feed through the export pipeline without
   * drift.
   */
  it('imports a pdfkit PDF and re-exports it via Broadset without errors', async () => {
    const sourceBytes = await buildPdfKitDoc((doc) => {
      doc.info.Producer = 'pdfkit cross-producer test';
      doc.text('Cross-producer round-trip', 50, 50);
    });

    const firstImport = await importPdfDocument(sourceBytes);
    const reExportedBytes = await exportPdfBytes(firstImport.document);
    const secondImport = await importPdfDocument(reExportedBytes);

    expect(reExportedBytes.length).toBeGreaterThan(100);
    expect(secondImport.warnings.find((w) => w.includes('failed'))).toBeUndefined();
  });

  /**
   * @description The Broadset re-export of a pdfkit-imported PDF MUST
   * carry the broadset: XMP packet so a third pass through the
   * importer recovers the (synthetic) Broadset document id — proving
   * the round-trip transforms a third-party PDF into a fully
   * Broadset-trackable one.
   */
  it('re-exported pdfkit PDFs gain a broadset: XMP packet for fast-path recovery', async () => {
    const sourceBytes = await buildPdfKitDoc((doc) => {
      doc.text('Document body for XMP enrichment', 50, 50);
    });

    const firstImport = await importPdfDocument(sourceBytes);
    const reExportedBytes = await exportPdfBytes(firstImport.document);
    const reExportedText = new TextDecoder('latin1').decode(reExportedBytes);

    expect(reExportedText).toContain('broadset:');
    expect(reExportedText).toContain('broadset:documentId');
  });
});
