import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import ts from 'typescript';

export const V1_RUNTIME_EXPORT_NAMES = [
  'ASSET_KINDS',
  'FORMATTER_IDS',
  'PROJECT_V1_LIMITS',
  'ProjectV1LimitError',
  'SAFE_FUNCTION_IDS',
  'VALUE_TYPES',
  'affine2dSchema',
  'appearanceSchema',
  'assetKindSchema',
  'assetSchema',
  'bindingSchema',
  'blendModeSchema',
  'blobReferenceSchema',
  'broadsetDocumentV1Schema',
  'broadsetProjectV1Schema',
  'canonicalizeProjectV1',
  'clipRemapSchema',
  'colorAdjustmentSchema',
  'colorValueSchema',
  'componentDefinitionSchema',
  'computeProjectSemanticHashV1',
  'concreteColorValueSchema',
  'createComponentAddressScope',
  'createDocumentAddressScope',
  'createPageAddressScope',
  'cueSchema',
  'diagnosticSchema',
  'effectSchema',
  'elementGeometrySchema',
  'elementSchema',
  'elementTransformSchema',
  'entityAddressSchema',
  'exposedPropertyBindingSchema',
  'exposedPropertyConstraintSchema',
  'exposedPropertySchema',
  'expressionAstSchema',
  'expressionInferenceContextSchema',
  'extensionEnvelopeSchema',
  'fillLayerSchema',
  'fontFamilyResourceSchema',
  'formatterPipelineSchema',
  'frameCountForDuration',
  'frameStartTicks',
  'gradientSchema',
  'idSchema',
  'inferBindingValueType',
  'inferExpressionStructuralValueType',
  'inferExpressionValueType',
  'inferFormatterPipelineValueType',
  'instanceAddressSchema',
  'interopDiagnosticSchema',
  'interopRecordSchema',
  'interopRegistrySchema',
  'interopSourceSchema',
  'interpolationMatchesType',
  'interpolationSchema',
  'jsonPointerSchema',
  'jsonValueSchema',
  'keyframeSchema',
  'lifecycleDefinitionSchema',
  'loadProjectV1Json',
  'loopDefinitionSchema',
  'markerSchema',
  'motionOutputProfileSchema',
  'normalizedRectSchema',
  'outputProfileSchema',
  'pageDefinitionSchema',
  'pageRootInstanceSchema',
  'paintSchema',
  'paragraphPropertiesSchema',
  'parseProjectV1Unknown',
  'printOutputProfileSchema',
  'projectResourcesSchema',
  'propertyTargetSchema',
  'rationalSchema',
  'reduceRational',
  'resolvePageInstanceElement',
  'resolveProjectEntityAddress',
  'resolvePropertyTargetContract',
  'resolvePropertyTargetContractFromIndexes',
  'resolvePropertyTargetContractInScope',
  'resolvePropertyTargetValueType',
  'resolvePropertyTargetValueTypeFromIndexes',
  'resolvePropertyTargetValueTypeInScope',
  'resolveTargetEntityAddress',
  'runPropertiesSchema',
  'sequenceActionSchema',
  'sequenceClipSchema',
  'sequenceSchema',
  'sha256DigestSchema',
  'sharedStyleSchema',
  'stateMachineSchema',
  'stateSchema',
  'stateValueSchema',
  'strokeLayerSchema',
  'structuredPathSchema',
  'surfaceDefinitionSchema',
  'swatchColorValueSchema',
  'swatchSchema',
  'templateGroupSchema',
  'textBodySchema',
  'textParagraphSchema',
  'textRunSchema',
  'ticksToFrame',
  'timebaseSchema',
  'trackSchema',
  'transitionSchema',
  'transitionTriggerSchema',
  'typedOverrideSchema',
  'typedValueMatchesSchema',
  'typedValueSchema',
  'utcTimestampSchema',
  'validateBooleanExpressionStructure',
  'validateBroadsetProjectV1Semantics',
  'validateTimebaseSemantics',
  'valueSchemaSchema',
  'valueSchemaValueType',
  'valueTypeSchema',
  'variableCollectionSchema',
  'viewModelSchema',
] as const;

export const V1_TYPE_EXPORT_NAMES = [
  'AddressScope',
  'Affine2D',
  'Appearance',
  'ArrowEnding',
  'Asset',
  'AssetBase',
  'AssetDerivative',
  'AssetIntrinsicMetadata',
  'AssetKind',
  'AssetLicense',
  'AssetProvenance',
  'AudioAsset',
  'AudioElement',
  'Binding',
  'BlendMode',
  'BlobReference',
  'BlobSource',
  'BroadsetDocumentV1',
  'BroadsetProjectV1',
  'ClipDefinition',
  'ClipRemap',
  'ClockElement',
  'ColorAdjustment',
  'ColorChannel',
  'ColorSpace',
  'ColorSpaceDefinition',
  'ColorValue',
  'ComponentDefinition',
  'ComponentElement',
  'ComponentInstanceElement',
  'ConcreteColorValue',
  'Cue',
  'DataAsset',
  'DescendantOverride',
  'Diagnostic',
  'DocumentColorConfiguration',
  'DocumentMetadata',
  'Effect',
  'Element',
  'ElementAccessibility',
  'ElementBase',
  'ElementGeometry',
  'ElementKind',
  'ElementTransform',
  'EntityAddress',
  'ExposedProperty',
  'ExposedPropertyBinding',
  'ExposedPropertyConstraint',
  'ExposedPropertyValue',
  'ExpressionAst',
  'ExpressionFieldContext',
  'ExpressionInferenceContext',
  'ExpressionTargetContext',
  'ExpressionVariableContext',
  'ExtensionEnvelope',
  'FillLayer',
  'FontAsset',
  'FontAxisValue',
  'FontFaceResource',
  'FontFamilyResource',
  'ForeignAsset',
  'ForeignElement',
  'FormatterId',
  'FormatterPipeline',
  'FormatterStep',
  'Gradient',
  'GradientStop',
  'GroupElement',
  'GuideDefinition',
  'IccProfileAsset',
  'Id',
  'ImageAsset',
  'ImageElement',
  'Insets',
  'InstanceAddress',
  'InteropDiagnostic',
  'InteropRecord',
  'InteropRegistry',
  'InteropSource',
  'Interpolation',
  'JsonPrimitive',
  'JsonValue',
  'Keyframe',
  'LifecycleDefinition',
  'LineSpacing',
  'LoopDefinition',
  'Marker',
  'MaskDefinition',
  'MotionOutputProfile',
  'NamedPercentageInsets',
  'NormalizedRect',
  'OpenTypeFeatureValue',
  'OutputProfile',
  'PageDefinition',
  'PageRootInstance',
  'Paint',
  'ParagraphProperties',
  'PathPoint',
  'PathSegment',
  'PatternRepeat',
  'PictureFit',
  'PluginElement',
  'PrintOutputProfile',
  'ProjectLoadOptions',
  'ProjectLoadResult',
  'ProjectMetadata',
  'ProjectParseResult',
  'ProjectResources',
  'ProjectV1LimitCode',
  'ProjectV1LimitError',
  'ProjectV1LimitViolation',
  'PropertyTarget',
  'PropertyTargetContract',
  'QrCodeElement',
  'Rational',
  'ResolvedTargetEntity',
  'RunProperties',
  'SafeFunctionId',
  'SampleDataSet',
  'Sequence',
  'SequenceAction',
  'SequenceClip',
  'Sha256Digest',
  'SharedStyle',
  'State',
  'StateMachine',
  'StateValue',
  'StrokeLayer',
  'StructuredPath',
  'SurfaceDefinition',
  'Swatch',
  'SwatchColorValue',
  'SwatchProducerAlias',
  'TemplateGroup',
  'TemplateGroupMember',
  'TextBody',
  'TextDecoration',
  'TextElement',
  'TextLayoutOptions',
  'TextList',
  'TextParagraph',
  'TextRun',
  'TextTab',
  'TickerElement',
  'TickerItem',
  'Timebase',
  'TintColorAdjustment',
  'Track',
  'Transition',
  'TransitionTrigger',
  'TypedOverride',
  'TypedValue',
  'UtcTimestamp',
  'ValueSchema',
  'ValueSchemaField',
  'ValueType',
  'VariableCollection',
  'VariableDefinition',
  'VectorAsset',
  'VectorElement',
  'VectorGeometryData',
  'VideoAsset',
  'VideoElement',
  'ViewModel',
  'ViewModelField',
] as const;

export const V1_RUNTIME_COLLISION_NAMES = [
  'assetSchema',
  'elementSchema',
  'keyframeSchema',
  'swatchSchema',
  'templateGroupSchema',
  'textBodySchema',
] as const;

export const V1_TYPE_COLLISION_NAMES = [
  'Asset',
  'AssetBase',
  'AssetKind',
  'AudioAsset',
  'ColorSpace',
  'DataAsset',
  'DocumentMetadata',
  'FontAsset',
  'IccProfileAsset',
  'ImageAsset',
  'Keyframe',
  'PatternRepeat',
  'Swatch',
  'TemplateGroup',
  'TemplateGroupMember',
  'TextBody',
  'VideoAsset',
] as const;

export const V1_PUBLIC_NAME_COLLISIONS = [...V1_TYPE_COLLISION_NAMES, ...V1_RUNTIME_COLLISION_NAMES] as const;

export const V1_COMPLETE_EXPORT_NAMES = [...new Set([...V1_RUNTIME_EXPORT_NAMES, ...V1_TYPE_EXPORT_NAMES])] as const;

interface CompilerExportInventory {
  readonly names: readonly string[];
  readonly runtimeNames: readonly string[];
  readonly typeNames: readonly string[];
}

export function readV1CompilerExportInventory(): CompilerExportInventory {
  const configPath = fileURLToPath(new URL('../../tsconfig.json', import.meta.url));
  const configFile = ts.readConfigFile(configPath, (path) => ts.sys.readFile(path));

  if (configFile.error !== undefined) {
    throw new Error(ts.flattenDiagnosticMessageText(configFile.error.messageText, '\n'));
  }

  const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, dirname(configPath));
  const program = ts.createProgram(parsed.fileNames, parsed.options);
  const barrelPath = fileURLToPath(new URL('./index.ts', import.meta.url));
  const barrel = program.getSourceFile(barrelPath);

  if (barrel === undefined) throw new Error(`Missing v1 barrel source: ${barrelPath}`);

  const checker = program.getTypeChecker();
  const moduleSymbol = checker.getSymbolAtLocation(barrel);

  if (moduleSymbol === undefined) throw new Error('Missing v1 barrel module symbol');

  const names: string[] = [];
  const runtimeNames: string[] = [];
  const typeNames: string[] = [];
  const typeFlags = ts.SymbolFlags.TypeAlias | ts.SymbolFlags.Interface | ts.SymbolFlags.Class | ts.SymbolFlags.Enum;

  for (const exported of checker.getExportsOfModule(moduleSymbol)) {
    const target = exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported;

    names.push(exported.name);
    if (target.flags & ts.SymbolFlags.Value) runtimeNames.push(exported.name);
    if (target.flags & typeFlags) typeNames.push(exported.name);
  }

  return { names, runtimeNames, typeNames };
}
